export const ALBUM_TYPE_LABELS: Record<string, string> = {
  mini_album: "Mini Album",
  full_album: "Album",
  single: "Single",
  digital_single: "Digital Single",
  repackage: "Repackage",
  fanmeeting: "Fanmeeting",
  fansign: "Fansign",
  season_greetings: "Season Greetings",
  membership_kit: "Membership Kit",
  platform_album: "Platform Album",
  lucky_draw: "Lucky Draw",
  photobook: "Photobook",
  concert: "Concert",
  event: "Event",
};
