import { SelectOption } from "@/src/types";

export const SHOP_OPTIONS: SelectOption[] = [
  // 🔢 Chiffres / Symboles
  { key: "1_1", label: "1:1" },
  { key: "11street", label: "11Street" },
  { key: "1st_music", label: "1st music" },
  { key: "1takes", label: "1takes" },
  { key: "1thek", label: "1theK" },
  { key: "4nologue", label: "4nologue" },
  { key: "7_eleven", label: "7 Eleven" },
  { key: "7net_shopping", label: "7net Shopping" },

  // 🅰️ A
  { key: "advertising_agency", label: "Advertising Agency" },
  { key: "aladin", label: "Aladin" },
  { key: "all_md", label: "ALL MD" },
  { key: "amazon", label: "Amazon" },
  { key: "amuze", label: "Amuze" },
  { key: "a_nation", label: "A-Nation" },
  { key: "apple_music", label: "Apple Music" },
  { key: "applewood", label: "Applewood" },
  { key: "araise", label: "Araise" },
  { key: "aismart", label: "AISMART" },
  { key: "australia", label: "Australia" },

  // 🅱️ B
  { key: "bandina", label: "Bandina" },
  { key: "barnes_noble", label: "Barnes&Noble" },
  { key: "baskin_robbins", label: "Baskin Robbins" },
  { key: "beatroad", label: "Beatroad" },
  { key: "bellygom", label: "Bellygom" },
  { key: "berriz", label: "Berriz" },
  { key: "bigpop", label: "Bigpop" },
  { key: "bizent", label: "Bizent" },
  { key: "blip", label: "Blip" },
  { key: "blue_dream_media", label: "Blue Dream Media" },
  { key: "bpm", label: "BPM" },
  { key: "broadcast", label: "Broadcast" },
  { key: "brokore_store", label: "Brokore store" },
  { key: "b_stage", label: "B.Stage" },
  { key: "bunjang", label: "Bunjang" },
  { key: "busking", label: "Busking" },

  // 🇨 C
  { key: "canada", label: "Canada" },
  { key: "cardiverse", label: "Cardiverse" },
  { key: "cash_bee", label: "Cash Bee" },
  { key: "cdjapan", label: "CDjapan" },
  { key: "cgv", label: "CGV" },
  { key: "china", label: "China" },
  { key: "choon_music", label: "Choon Music" },
  { key: "cokodive", label: "Cokodive" },
  { key: "come_back_show", label: "Come Back Show" },
  { key: "common", label: "Common" },
  { key: "countdown_live", label: "Countdown live" },
  { key: "counting_stars", label: "Counting Stars" },
  { key: "cu", label: "CU" },
  { key: "culture_bridge", label: "Culture Bridge" },

  // 🇩 D
  { key: "d2c", label: "D2C" },
  { key: "daily_duck", label: "Daily Duck" },
  { key: "danal", label: "Danal" },
  { key: "dear_my_muse", label: "Dear My Muse" },
  { key: "decorating_event", label: "Decorating Event" },
  { key: "dingo_live", label: "Dingo Live" },
  { key: "dmc_music", label: "Dmc Music" },
  { key: "drink", label: "Drink" },

  // 🇪 E
  { key: "emart24", label: "emart24" },
  { key: "europe", label: "Europe" },
  { key: "everline", label: "Everline" },

  // 🇫 F
  { key: "fancafe", label: "Fancafe" },
  { key: "fanclub", label: "Fanclub" },
  { key: "fan_party", label: "Fan Party" },
  { key: "fanplee", label: "Fanplee" },
  { key: "fans", label: "Fans" },
  { key: "fatirkshop", label: "Fatirkshop" },
  { key: "first_press", label: "First Press" },
  { key: "flippers_listening_party", label: "Flipper's Listening Party" },
  { key: "flnk", label: "FLNK" },
  { key: "flumeride", label: "Flumeride" },
  { key: "fnac", label: "Fnac" },
  { key: "fnc_store", label: "FNC Store" },
  { key: "fromm", label: "Fromm" },

  // 🇬 G
  { key: "gmarket", label: "Gmarket" },
  { key: "gmmtv", label: "GMMTV" },
  { key: "green_universe_music", label: "Green Universe Music" },
  { key: "group", label: "Group" },
  { key: "gs25", label: "GS25" },

  // 🇭 H
  { key: "hb_channel", label: "HB Channel" },
  { key: "hello82", label: "Hello82" },
  { key: "hello82_eu", label: "Hello82 EU" },
  { key: "hello82_uk", label: "Hello82 UK" },
  { key: "hello82_us", label: "Hello82 US" },
  { key: "hello_live", label: "Hello Live" },
  { key: "hightier", label: "Hightier" },
  { key: "hmv", label: "HMV" },
  { key: "hottracks", label: "Hottracks" },
  { key: "house_of_kpop", label: "House Of Kpop" },
  { key: "hybe_insight", label: "Hybe Insight" },

  // 🇮 I
  { key: "idou_stage", label: "Idou Stage" },
  { key: "i_five", label: "I Five" },
  { key: "indonesia", label: "Indonesia" },
  { key: "inkigayo", label: "Inkigayo" },
  { key: "inside_record", label: "INSIDE RECORD" },
  { key: "interasia", label: "Interasia" },
  { key: "international", label: "International" },
  { key: "interpark", label: "Interpark" },
  { key: "invitation_event", label: "Invitation event" },
  { key: "its_live", label: "It's Live!" },
  { key: "itta", label: "Itta" },

  // 🇯 J
  { key: "japan", label: "Japan" },
  { key: "jingdong", label: "Jingdong" },
  { key: "jjmuze", label: "Jjmuze" },
  { key: "joeun_music", label: "Joeun Music" },
  { key: "jump_up", label: "Jump Up" },
  { key: "jyp_shop", label: "JYP Shop" },
  { key: "jyp_soundwave", label: "JYP SoundWave" },

  // 🇰 K
  { key: "kakaotalk", label: "Kakaotalk" },
  { key: "keapop", label: "Keapop" },
  { key: "kglobal_live", label: "Kglobal Live" },
  { key: "k_idol", label: "K Idol" },
  { key: "kiss_ent", label: "Kiss Ent" },
  { key: "k_monstar", label: "K-Monstar" },
  { key: "km_station", label: "KM Station" },
  { key: "knpops", label: "Knpops" },
  { key: "kooky", label: "Kooky" },
  { key: "kpop_agent", label: "Kpop Agent" },
  { key: "kpop_bestie", label: "Kpop Bestie" },
  { key: "kpop_hub", label: "Kpop Hub" },
  { key: "kpopmart", label: "Kpopmart" },
  { key: "kpop_merch", label: "Kpop Merch" },
  { key: "kpopnara", label: "Kpopnara" },
  { key: "kpop_planet", label: "Kpop Planet" },
  { key: "kpopstore", label: "Kpopstore" },
  { key: "kpop_together", label: "Kpop Together" },
  { key: "kq_shop", label: "KQ Shop" },
  { key: "krzd", label: "KRZD" },
  { key: "kstarhit", label: "Kstarhit" },
  { key: "ktown4u", label: "Ktown4u" },
  { key: "kwangya", label: "KWANGYA" },

  // 🇱 L
  { key: "latam", label: "Latam" },
  { key: "lazada", label: "Lazada" },
  { key: "line_friends", label: "Line Friends" },
  { key: "listening_party", label: "Listening Party" },
  { key: "live_shopping", label: "Live Shopping" },
  { key: "lotte_duty_free", label: "Lotte Duty Free" },
  { key: "lucky_draw", label: "Lucky Draw" },

  // 🇲 M
  { key: "m2u", label: "M2U" },
  { key: "makestar", label: "Makestar" },
  { key: "marvel_skiyaki", label: "Marvel Skiyaki" },
  { key: "mcountdown", label: "MCountdown" },
  { key: "mecima", label: "Mecima" },
  { key: "mihwadang", label: "Mihwadang" },
  { key: "million_music", label: "MillionMusic" },
  { key: "minirecord", label: "Minirecord" },
  { key: "mins_studio", label: "Mins Studio" },
  { key: "mk_media", label: "MK Media" },
  { key: "mnet_plus_chat", label: "Mnet Plus Chat" },
  { key: "mnet_plus_merch", label: "Mnet plus merch" },
  { key: "mokketshop", label: "Mokketshop" },
  { key: "mubeat", label: "MuBeat" },
  { key: "mu_mo", label: "Mu-mo" },
  { key: "muse", label: "Muse" },
  { key: "music2u", label: "Music2U" },
  { key: "music_art", label: "Music Art" },
  { key: "music_bank", label: "Music Bank" },
  { key: "music_core", label: "Music Core" },
  { key: "music_and_drama", label: "Music & Drama" },
  { key: "music_korea", label: "Music Korea" },
  { key: "music_plant", label: "Music Plant" },
  { key: "music_scale", label: "Music Scale" },
  { key: "musinsa", label: "Musinsa" },
  { key: "muvve", label: "Muvve" },
  { key: "mwave", label: "Mwave" },
  { key: "my_music_taste", label: "MyMusicTaste" },
  { key: "my_star_goods", label: "My Star Goods" },

  // 🇳 N
  { key: "namil_music", label: "Namil Music" },
  { key: "nanyi", label: "Nanyi" },
  { key: "naver_live", label: "Naver Live" },
  { key: "nearbymusic", label: "Nearbymusic" },
  { key: "nemoz", label: "Nemoz" },
  { key: "neotokyo", label: "Neotokyo" },
  { key: "neowing", label: "Neowing" },
  { key: "nolae", label: "Nolae" },
  { key: "ny_music", label: "NY Music" },

  // 🇴 O
  { key: "official_store", label: "Official Store" },
  { key: "offline", label: "Offline" },
  { key: "olive_young", label: "OliveYoung" },
  { key: "online", label: "Online" },
  { key: "olwhat", label: "olwhat" },

  // 🇵 P
  { key: "philippines", label: "Philippines" },
  { key: "photoism", label: "Photoism" },
  { key: "ploghveykpop", label: "Ploghveykpop" },
  { key: "pop_up_store", label: "Pop-Up Store" },
  { key: "pop_up_store_pocket_holder", label: "Pop-Up Store Pocket Holder" },
  { key: "powerstation", label: "PowerStation" },
  { key: "pulp", label: "Pulp" },

  // 🇶 Q
  { key: "qoo10", label: "Qoo10" },
  { key: "qq10", label: "QQ10" },
  { key: "qq_music", label: "QQ Music" },

  // 🇷 R
  { key: "rakuten", label: "Rakuten" },
  { key: "rbw", label: "RBW" },
  { key: "real_world", label: "Real World" },
  { key: "release_party", label: "Release Party" },
  { key: "richining", label: "Richining" },
  { key: "riser_music", label: "RISER MUSIC" },
  { key: "rising_star", label: "Rising Star" },

  // 🇸 S
  { key: "sanok", label: "Sanok" },
  { key: "set", label: "Set" },
  { key: "shinseido", label: "Shinseido" },
  { key: "shopee", label: "Shopee" },
  { key: "shopee_thai", label: "Shopee Thai" },
  { key: "showcase", label: "Showcase" },
  { key: "singapore", label: "Singapore" },
  { key: "sixkshop", label: "Sixkshop" },
  { key: "sm_global_shop", label: "SM Global Shop" },
  { key: "smileme", label: "SmileMe" },
  { key: "smtown", label: "SMTOWN" },
  { key: "snowshop", label: "Snowshop" },
  { key: "sony", label: "Sony" },
  { key: "soundbomb_360", label: "Soundbomb 360" },
  { key: "soundwave", label: "SoundWave" },
  { key: "south_korea", label: "South Korea" },
  { key: "special_gift", label: "Special Gift" },
  { key: "sponge_music", label: "Sponge Music" },
  { key: "spotify", label: "Spotify" },
  { key: "starlike_music", label: "Starlike Music" },
  { key: "starone", label: "Starone" },
  { key: "starriver", label: "Starriver" },
  { key: "starriver_china", label: "Starriver China" },
  { key: "starship", label: "Starship" },
  { key: "streaming", label: "Streaming" },
  { key: "studio_choom", label: "Studio Choom" },
  { key: "subk_shop", label: "Subk Shop" },
  { key: "synnara", label: "Synnara" },

  // 🇹 T
  { key: "taiwan", label: "Taiwan" },
  { key: "talkport", label: "Talkport" },
  { key: "tance", label: "TANCE" },
  { key: "target", label: "Target" },
  { key: "thailand", label: "Thailand" },
  { key: "the_dnd", label: "The DnD" },
  { key: "the_show", label: "The Show" },
  { key: "tiktok", label: "TikTok" },
  { key: "tokopedia", label: "Tokopedia" },
  { key: "toktoq", label: "TokToq" },
  { key: "tong", label: "Tong" },
  { key: "tou_global", label: "Tou Global" },
  { key: "tower_records", label: "Tower Records" },
  { key: "trinity", label: "Trinity" },
  { key: "tsutaya", label: "Tsutaya" },
  { key: "twitter", label: "Twitter" },

  // 🇺 U
  { key: "unboxing_event", label: "Unboxing Event" },
  { key: "unit", label: "Unit" },
  { key: "universal_music_store", label: "Universal Music Store" },
  { key: "universe_event", label: "Universe Event" },
  { key: "us", label: "US" },

  // 🇻 V
  { key: "victor", label: "Victor" },

  // 🇼 W
  { key: "walmart", label: "Walmart" },
  { key: "weidian_xiongbao", label: "Weidian Xiongbao" },
  { key: "weverse", label: "Weverse" },
  { key: "weverse_exclusive", label: "Weverse Exclusive" },
  { key: "weverse_japan_membership", label: "Weverse Japan Membership" },
  { key: "weverse_showcase", label: "Weverse Showcase" },
  { key: "weverse_us", label: "Weverse US" },
  { key: "whoop", label: "Whoop" },
  { key: "whosfan", label: "Whosfan" },
  { key: "winner", label: "Winner" },
  { key: "withdrama", label: "WithDrama" },
  { key: "withdrama_video_call", label: "WithDrama Video Call" },
  { key: "withfans", label: "WithFans" },
  { key: "withmuu", label: "WithMuu" },
  { key: "wondergoo", label: "WonderGOO" },
  { key: "wonderwall", label: "Wonderwall" },

  // 🇾 Y
  { key: "yes24", label: "Yes24" },
  { key: "yes24_compact", label: "Yes24 Compact" },
  { key: "yes24_standard", label: "Yes24 Standard" },
  { key: "yeti_mall", label: "Yeti Mall" },
  { key: "y_global", label: "Y Global" },
  { key: "yg_select", label: "YG Select" },
  { key: "yg_select_china", label: "YG Select China" },
  { key: "yg_select_thailand", label: "YG Select Thailand" },
  { key: "yizhiyu", label: "Yizhiyu" },
  { key: "young_poong_bookstore", label: "Young Poong Bookstore" },
  { key: "youtube", label: "YouTube" },
];
